- R/lamindb_setup__connect_instance.R
- R/lamindb_setup__core__settings_load.R
- R/lamindb_setup__core__settings_store.R
I accidentally entered into a rabbithole porting code from lamindb_setup, something we didn't want to spend time on at this stage.
Instead of deleting the code, I might as well commit the code and create a draft PR. Perhaps we can come back to it at a later stage.
> Reading user and instance settings

- CHANGELOG.md
- R/settings_store.R
* Fixed the parsing of the env files in `~/.lamin` due to changes in the lamindb-setup Python package (PR #xx).
>  Fixed the parsing of the env files

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- CHANGELOG.md
* Define a current user and current instance with lamin-cli prior to testing and generating documentation in the CI.
> Log into Lamin in CI

- CHANGELOG.md
- vignettes/usage.Rmd
- vignettes/usage.qmd
* Add vignette to showcase laminr usage.
> Add usage vignette

- CHANGELOG.md
- R/InstanceAPI.R
- R/InstanceSettings.R
- tests/testthat/test-instance_api.R
* Added unit test for the InstanceAPI class (PR #30).
* Add alternative error message when no message is returned from the API (PR #30).
> Improve error messages

- CHANGELOG.md
- R/Artifact.R
- R/Field.R
- R/Instance.R
- R/InstanceAPI.R
- R/InstanceSettings.R
- R/Module.R
- R/Record.R
- R/Registry.R
- R/UserSettings.R
- R/printing.R
- README.md
Add `print()` and `to_string()` methods to the remaining R6 classes. Output tries to replicate the Python formatting except for some cases where the corresponding Python object doesn't have a print output.
> Add printing to remaining classes

- .Rbuildignore
- CHANGELOG.md
- DESCRIPTION
- man/laminr-package.Rd
Make a couple of changes to the docs
> update version, add luke as an author

- CHANGELOG.md
- R/InstanceAPI.R
- R/Registry.R
- man/Registry.Rd
- man/laminr-package.Rd
- tests/testthat/test-Registry.R
- tests/testthat/test-instance_api.R
Adds a `get_records()` method to the `InstanceAPI` class which performs the API call to retrieve record summary information and a `df()` method to the `Registry` class which makes the required API calls to get the requested number of records and formats the returned information as a `data.frame()`. This tries to be semi-smart to limit the number of API calls.
Fixes #43 
Checks:
> Add get_records() to API and df() to Registry

- CHANGELOG.md
- R/Instance.R
- R/Module.R
- README.md
Remove link tables from the print output for `Instance` and `Module` classes.
Fixes #52
> Remove link tables from print output

- CHANGELOG.md
- DESCRIPTION
- R/Artifact.R
- R/utils.R
- README.md
- README.qmd
- tests/testthat/test-utils.R
- vignettes/usage.Rmd
Added a function that checks if suggested packages are installed and gives a nice error with installation instructions if not. 
Updated installation docs with instructions for installing suggested dependencies and information on what they are used for.
Fixes #46 
Fixes #47
> Add check_requires() function and update installation docs

- CHANGELOG.md
- R/InstanceAPI.R
- tests/testthat/test-instance_api.R
Add the status code to the API error message and update the test for when records don't exist
Fixes #44
> Improve API error messages

- CHANGELOG.md
- R/Instance.R
- R/Registry.R
- README.md
- man/Instance.Rd
- vignettes/architecture.qmd
- vignettes/development.qmd
> Add tracking of runs

- .github/workflows/pkgdown.yaml
**Related to:** Fixes #91 
Use the pre-release version of Quarto in the `pkgdown` workflow so the architecture diagrams are rendered correctly.
> Fix Mermid diagrams in vignettes

- vignettes/laminr.Rmd
The most important change here is establishing a clearer and simpler order within the setup section.
I'd almost be tempted to install laminr after doing the python stuff, but I left it like it was for now.
> Polish the get-started guide

- vignettes/laminr.Rmd
This is meant to resolve the two below issues:
- https://github.com/laminlabs/laminr/issues/103
- https://github.com/laminlabs/laminr/issues/108
> Update `get-started` with resolutions of questions from demo

- CHANGELOG.md
- R/Artifact.R
- R/Instance.R
- vignettes/development.qmd
**Related to:** Fixes #98 
- Add Python **lamindb** to all instances (if available)
- Still warn for the default instance if not
- Use Python in `Artifact$cache()` (if available)
- Fall back to the API if not with a warning
> ✨ Tracking artifacts loaded from other instances

- R/InstanceAPI.R
- R/connect.R
- R/utils.R
My JWT token expired, but trying to connect to an instance resulted in the following error:
```r
> devtools::install()
> library(laminr)
> db <- connect("laminlabs/cellxgene")
db$Artifact
Error in `rlang::abort()`:
! `message` must be a character vector, not a list.
Run `rlang::last_trace()` to see where the error occurred.
```
> 🐛 Fix error message when fetching the instance details fails

- R/install.R
Try to attach the created environment in `install_lamindb()` and give feedback if not successful.
> 🚸 Check attaching to environment in install_lamindb()

- .github/workflows/R-CMD-check.yaml
- CHANGELOG.md
- DESCRIPTION
- R/Instance.R
- R/InstanceAPI.R
- R/connect.R
- R/install.R
- R/settings_load.R
- man/lamin_login.Rd
Automatically refresh user tokens when trying to connect to an instance with an invalid token instead of failing with an error message:
- Update `lamin_login()` to use a stored user handle when none is supplied
- Move setting the default instance to `create_instance()` so that it isn't set before a successful connection
- Add a `refresh` argument to `.get_user_settings()` to force ignoring the cache
- Check if the request failed in `api$get_schema()` due to an invalid token and if so call `lamin_login()`
to refresh the token and make a new request with updated he headers
> 🚸 Automatically refresh user tokens

- .github/workflows/R-CMD-check.yaml
- .github/workflows/test-docs.yaml
- .github/workflows/test-unit.yaml
Rather than constantly running CI against pre-releases, we're now dispatching to laminr prior to making a release.
This keeps the overall runners smaller and is consistent with the many other integration tests we're running prior to making a release.
I've also slightly changed the naming conventions of the workflow files and hope that we can ultimately consolidate it in a single `test.yaml` or `build.yaml` so that things are easy to understand.
In particular the `test-docs.yaml` workflow can be simplified and we'll do so in future PRs.
Also added Slack notifs for dispatch events.
> ♻️ Dispatch CI from pre-release event in lamindb

- R/checks.R
- R/lamin_cli.R
- tests/testthat/test-checks.R
**Related to:** #164 
Allow running `lamin_connect()` multiple times with the same instance. Done by adding an instance argument to `check_default_instance()` that skips the check if it matches the current default instance.
Fixes #164.
> 🐛 Allow running `lamin_connect()` multiple times

- .github/workflows/test-docs.yaml
- test-docs/r-quickstart.R
This function returns that `bionty` isn't configured even though it clearly is in `test-docs`.
https://github.com/laminlabs/laminr/blob/8a85a7c521f1a5a424dbc02dc0d1c68f5e1c1ee1/R/checks.R#L119-L144
Similarly, other calls within Python indicate that `bionty` isn't installed. This PR tries to debug and fix these issues.
> 👷 Log bionty version

- CHANGELOG.md
- R/lamindb.R
Adds a workaround for pak::lockfile_create throwing errors during the finish process.
**Related to:** #195 
If pak::lockfile_create fails for some reason or another, it will show the following error message:
<details><summary>Code</summary>
```r
pkgs <- c("thispackagedoesnotexist")
pkg_repos <- c()
run_dir <- tempdir()
tryCatch(
withr::with_options(
list(repos = unique(c(pkg_repos, getOption("repos")))),
{
pak::lockfile_create(
pkg = pkgs,
lockfile = file.path(run_dir, "r_pak_lockfile.json")
)
}
),
error = function(err) {
cli::cli_warn(
c(
"Failed to create the lockfile for the run using pak.",
"i" = "Please reach out via GitHub or Slack if you need help.",
"x" = "Error message: {err}"
)
)
}
)
```
</details>
Error message:
✖ Creating lockfile /tmp/Rtmpw3CZ7F/r_pak_lockfile.json [1.6s] …
> :bug: Surround pak lockfile creation with try-catch to avoid breaking the finish process

- R/utils.R
Handle edge case where the document context can be missing an `id` value in `detect_path()`. Came up when testing things in Positron but might happen in other places.
> 🐛 Handle NULL `doc_context$id` in `detect_path()`
