laminlabs/laminr

- R/InstanceAPI.R
Somehow these ended up in private, moving them back to public so they work
> Make InstanceAPI print methods public

- CHANGELOG.md
- R/Artifact.R
Set `progress = TRUE` in `Artifact$cache()`
> Add progress bar

- .github/workflows/R-CMD-check.yaml
- CHANGELOG.md
* Manually install OpenBLAS on macOS (PR #62).
* Switch to Python 3.12 for being able to install scipy on macOS (PR #66).
> Fix macOS runner

- CHANGELOG.md
- R/Instance.R
- man/Instance.Rd
- Swap argument order in `Instance$track()` to match Python
- Improve Python error handling in `Instance$track()`
> Minor fixes to Instance$track()

- vignettes/laminr.Rmd
Cosmetic fixes. See discussion points in the PR below:
- https://github.com/laminlabs/laminr/pull/97
> Cosmetic fixes to `get-started`

- README.md
**Related to:** Fixes #99  
Remove the feature warning from `README`
> Remove feature warning from README

- .github/pull_request_template.md
**Related to:** #121 
Adds instruction to PR template saying to set an emoji in the heading
> 📝 Add gitmoji instructions to PR template

- CHANGELOG.md
- DESCRIPTION
- R/connect.R
- man/install_lamindb.Rd
- man/lamin_connect.Rd
> 🚸 Prepare for release 0.3.1

- CHANGELOG.md
- DESCRIPTION
- R/Instance.R
- _pkgdown.yml
* Update changelog and version number
* Fix usage of utils function
* Derive pkgdown develop mode from pkg version number
> :rocket: Release 0.4.0

- .github/workflows/rhub.yaml
Add the rhub GitHub Actions workflow to help with identifying CRAN issues
> 👷 Add rhub GHA workflow

- CHANGELOG.md
- DESCRIPTION
Increase the R version dependency to >= 4.1.0 to avoid a `NOTE` in checks
> ⬆️ Bump R dependency to >= 4.1

- CHANGELOG.md
- DESCRIPTION
- R/install.R
> Prep release 1.0.0

- CHANGELOG.md
- DESCRIPTION
- R/file_loaders.R
- tests/testthat/test-file_loaders.R
Update dependencies to fix CRAN checks
Fixes #155 
> ⬆️ Update dependencies

- CHANGELOG.md
- DESCRIPTION
Update package files for v1.0.1
> :memo: Prepare for release 1.0.1

- test-docs/r-quickstart.R
- https://github.com/laminlabs/lamin-docs/pull/232
> ♻️ Make R and Python quickstarts parallel

- DESCRIPTION
- R/lamindb.R
- R/packages.R
**Related to:** Fixes #173 
Modify `finish` to save a **{pak}** lockfile to the cache directory, correctly named for that run.
> ✨ Track R environment

- CHANGELOG.md
- R/lamin_cli.R
Make sure temporary instance storage is cleared so it can be cleaned up correctly
> 🐛 Clear temporary instance storage

- CHANGELOG.md
- R/Artifact.R
- R/Collection.R
- R/Registry.R
- R/Transform.R
- R/arguments.R
- R/lamindb.R
- R/utils.R
- R/view.R
- R/wrap-python.R
Updates wrapping of Python functions and overwritten methods so that arguments are properly inherited. This allows automatically wrapped methods and (most) overwritten methods to automatically adjust to any changes in arguments in new `lamindb` versions. It also improves autocomplete for users.
- Restore functions for extracting arguments from Python functions
- Add a new `get_r_arguments()` function
- Add a new `make_wrapper_function()` function
- Update wrapping to use the new functionality
> ✨ Update wrapping to inherit Python function arguments

- DESCRIPTION
> :rocket: Release 1.1.1

- CHANGELOG.md
- R/require.R
- R/status.R
Add a minimal `scipy` requirement to `require_lamindb()` to avoid trying to compile and install `scipy==1.6` as in #206 
> ⬆️ Add minimal scipy requirement

- CHANGELOG.md
- DESCRIPTION
- R/require.R
Modify `require_lamindb()` so that development dependencies are installed from submodules of the **lamindb** GitHub repository instead of the `main` branch of the individual repositories. This should make sure the expected versions are installed and fix CI issues.
> ⬆️ Install development dependencies from submodules
